# Generated by Django 5.2.4 on 2025-07-18 19:17

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Empresa',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome_fantasia', models.CharField(max_length=200, unique=True)),
                ('razao_social', models.CharField(blank=True, max_length=200)),
                ('cidade', models.CharField(blank=True, max_length=200)),
                ('estado', models.CharField(blank=True, max_length=2)),
                ('email', models.EmailField(blank=True, default='', max_length=254)),
                ('cnpj', models.CharField(blank=True, max_length=18)),
                ('telefone', models.CharField(blank=True, max_length=20)),
                ('logo', models.ImageField(blank=True, null=True, upload_to='logos_empresas/')),
            ],
        ),
        migrations.CreateModel(
            name='Cliente',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome_razao_social', models.CharField(max_length=200, verbose_name='Nome / Razão Social')),
                ('cpf_cnpj', models.CharField(max_length=18, unique=True, verbose_name='CPF/CNPJ')),
                ('telefone', models.CharField(blank=True, max_length=20)),
                ('email', models.EmailField(blank=True, max_length=254)),
                ('endereco_principal', models.CharField(blank=True, max_length=255, verbose_name='Endereço Principal')),
                ('cidade', models.CharField(blank=True, max_length=100)),
                ('estado', models.CharField(blank=True, max_length=2)),
                ('empresa', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.empresa')),
            ],
            options={
                'verbose_name': 'Cliente',
                'verbose_name_plural': 'Clientes',
            },
        ),
        migrations.CreateModel(
            name='Poco',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('identificador_poco', models.CharField(help_text="Ex: 'Poço Sede da Fazenda', 'Poço Filial 1'", max_length=100, verbose_name='Identificador do Poço')),
                ('data_perfuração_inicial', models.DateField(verbose_name='Data da Perfuração')),
                ('endereco_completo', models.CharField(max_length=255, verbose_name='Endereço do Poço')),
                ('cidade', models.CharField(max_length=100)),
                ('estado', models.CharField(max_length=2)),
                ('foto_principal', models.ImageField(blank=True, null=True, upload_to='fotos_pocos/', verbose_name='Foto do Poço')),
                ('localizacao_mapa', models.CharField(blank=True, max_length=255, null=True, verbose_name='Localização Geografica')),
                ('profundidade_total', models.DecimalField(decimal_places=2, help_text='Em metros', max_digits=7)),
                ('diametro_poco', models.DecimalField(decimal_places=2, help_text='Em polegadas', max_digits=5)),
                ('tubulacao_material', models.CharField(blank=True, help_text='Ex: PVC, Aço Galvanizado', max_length=50, verbose_name='Material da Tubulação')),
                ('modelo_bomba_instalada', models.CharField(blank=True, max_length=100, verbose_name='Modelo da Bomba')),
                ('modelo_gerador', models.CharField(blank=True, max_length=100, verbose_name='Modelo do Gerador')),
                ('painel_comando', models.CharField(blank=True, max_length=100, verbose_name='Painel de Comando')),
                ('profundidade_bomba', models.DecimalField(blank=True, decimal_places=2, max_digits=7, null=True, verbose_name='Profundidade da Bomba (metros)')),
                ('profundidade_injetor', models.DecimalField(blank=True, decimal_places=2, max_digits=7, null=True, verbose_name='Profundidade do Injetor (metros)')),
                ('cabo_eletrico', models.CharField(blank=True, max_length=100, verbose_name='Cabo Elétrico')),
                ('cabo_nautico', models.CharField(blank=True, max_length=100, verbose_name='Cabo Náutico (Segurança)')),
                ('fusivel_disjuntor', models.CharField(blank=True, max_length=100, verbose_name='Fusível / Disjuntor')),
                ('contator', models.CharField(blank=True, max_length=100, verbose_name='Contator')),
                ('rele_termico', models.CharField(blank=True, max_length=100, verbose_name='Relé Térmico')),
                ('capacitores', models.CharField(blank=True, max_length=100, verbose_name='Capacitores')),
                ('equipamento_assistencia', models.TextField(blank=True, verbose_name='Equipamento de Assistência Utilizado')),
                ('cliente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pocos', to='core.cliente')),
            ],
            options={
                'verbose_name': 'Poço',
                'verbose_name_plural': 'Poços',
            },
        ),
        migrations.CreateModel(
            name='Manutencao',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data_manutencao', models.DateField(verbose_name='Data da Manutenção')),
                ('tipo_servico', models.CharField(help_text='Ex: Manutenção Preventiva, Troca de Bomba, Limpeza', max_length=100)),
                ('nivel_estatico_medido', models.DecimalField(decimal_places=2, help_text='Em metros', max_digits=7, verbose_name='Nível Estático')),
                ('nivel_dinamico_medido', models.DecimalField(decimal_places=2, help_text='Em metros', max_digits=7, verbose_name='Nível Dinâmico')),
                ('vazao_medida', models.DecimalField(decimal_places=2, help_text='Em m³/h', max_digits=7, verbose_name='Vazão')),
                ('amperagem_trabalho', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True, verbose_name='Amperagem')),
                ('tensao_trabalho', models.IntegerField(blank=True, null=True, verbose_name='Tensão (Volts)')),
                ('observacoes', models.TextField(blank=True, verbose_name='Observações do Serviço')),
                ('operador_responsavel', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='Operador Responsável')),
                ('poco', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='historico_manutencoes', to='core.poco', verbose_name='Poço')),
            ],
            options={
                'verbose_name': 'Registro de Manutenção',
                'verbose_name_plural': 'Registros de Manutenção',
                'ordering': ['-data_manutencao'],
            },
        ),
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('empresa', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.empresa')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='profile', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
