# Generated by Django 5.2.4 on 2025-07-18 21:20

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='poco',
            name='foto_principal',
        ),
        migrations.CreateModel(
            name='FotoPoco',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('imagem', models.ImageField(upload_to='fotos_pocos/')),
                ('descricao', models.CharField(blank=True, max_length=200, verbose_name='Descrição (Opcional)')),
                ('is_principal', models.BooleanField(default=False, verbose_name='Marcar como Foto Principal')),
                ('data_upload', models.DateTimeField(auto_now_add=True)),
                ('poco', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='fotos', to='core.poco')),
            ],
            options={
                'ordering': ['-is_principal', '-data_upload'],
            },
        ),
    ]
