# Generated by Django 5.2.4 on 2026-07-10 22:06

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_bomba_fotobomba_ordemservico_orcamento_itemos'),
    ]

    operations = [
        migrations.AddField(
            model_name='bomba',
            name='cliente_proprietario',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='bombas_proprietarias', to='core.cliente', verbose_name='Cliente Proprietário'),
        ),
        migrations.AddField(
            model_name='bomba',
            name='is_reserva',
            field=models.BooleanField(default=False, verbose_name='Bomba de Reserva'),
        ),
        migrations.AddField(
            model_name='bomba',
            name='status',
            field=models.CharField(choices=[('disponivel', 'Disponível'), ('em_uso', 'Em Uso'), ('manutencao', 'Em Manutenção')], default='disponivel', max_length=15, verbose_name='Status'),
        ),
    ]
