# Generated by Django 5.2.4 on 2025-07-15 14:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_cliente_cidade_cliente_estado'),
    ]

    operations = [
        migrations.AddField(
            model_name='poco',
            name='cabo_eletrico',
            field=models.CharField(blank=True, max_length=100, verbose_name='Cabo Elétrico'),
        ),
        migrations.AddField(
            model_name='poco',
            name='cabo_nautico',
            field=models.CharField(blank=True, max_length=100, verbose_name='Cabo Náutico (Segurança)'),
        ),
        migrations.AddField(
            model_name='poco',
            name='capacitores',
            field=models.CharField(blank=True, max_length=100, verbose_name='Capacitores'),
        ),
        migrations.AddField(
            model_name='poco',
            name='contator',
            field=models.CharField(blank=True, max_length=100, verbose_name='Contator'),
        ),
        migrations.AddField(
            model_name='poco',
            name='equipamento_assistencia',
            field=models.TextField(blank=True, verbose_name='Equipamento de Assistência Utilizado'),
        ),
        migrations.AddField(
            model_name='poco',
            name='fusivel_disjuntor',
            field=models.CharField(blank=True, max_length=100, verbose_name='Fusível / Disjuntor'),
        ),
        migrations.AddField(
            model_name='poco',
            name='profundidade_bomba',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=7, null=True, verbose_name='Profundidade da Bomba (metros)'),
        ),
        migrations.AddField(
            model_name='poco',
            name='profundidade_injetor',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=7, null=True, verbose_name='Profundidade do Injetor (metros)'),
        ),
        migrations.AddField(
            model_name='poco',
            name='rele_termico',
            field=models.CharField(blank=True, max_length=100, verbose_name='Relé Térmico'),
        ),
    ]
