# Generated by Django 5.2.4 on 2026-07-10 22:30

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_bomba_cliente_proprietario_bomba_is_reserva_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='ordemservico',
            name='data_entrada',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Data/Hora de Entrada'),
        ),
        migrations.AddField(
            model_name='ordemservico',
            name='data_saida',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Data/Hora de Saída'),
        ),
        migrations.CreateModel(
            name='FotoMovimentacao',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('imagem', models.ImageField(upload_to='fotos_movimentacao/')),
                ('descricao', models.CharField(blank=True, max_length=200, verbose_name='Descrição')),
                ('tipo_foto', models.CharField(choices=[('entrada', 'Foto de Entrada'), ('saida', 'Foto de Saída'), ('servico', 'Foto do Serviço')], default='servico', max_length=10, verbose_name='Tipo da Foto')),
                ('data_upload', models.DateTimeField(auto_now_add=True)),
                ('os', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='fotos_movimentacao', to='core.ordemservico')),
            ],
            options={
                'verbose_name': 'Foto de Movimentação',
                'verbose_name_plural': 'Fotos de Movimentação',
                'ordering': ['tipo_foto', '-data_upload'],
            },
        ),
    ]
