# Generated by Django 5.2.4 on 2025-07-16 19:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_poco_cabo_eletrico_poco_cabo_nautico_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='poco',
            name='localizacao_mapa',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Localização Geografica'),
        ),
    ]
