# Generated by Django 5.2.4 on 2026-07-11 11:11

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_ordemservico_data_entrada_ordemservico_data_saida_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Funcionario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome_completo', models.CharField(max_length=200, verbose_name='Nome Completo')),
                ('cpf', models.CharField(max_length=14, unique=True, verbose_name='CPF')),
                ('cargo', models.CharField(choices=[('tecnico', 'Técnico'), ('mecanico', 'Mecânico'), ('eletricista', 'Eletricista'), ('motorista', 'Motorista'), ('auxiliar', 'Auxiliar'), ('supervisor', 'Supervisor'), ('administrativo', 'Administrativo'), ('outro', 'Outro')], default='tecnico', max_length=20, verbose_name='Cargo')),
                ('telefone', models.CharField(blank=True, max_length=20, verbose_name='Telefone')),
                ('email', models.EmailField(blank=True, max_length=254, verbose_name='E-mail')),
                ('ativo', models.BooleanField(default=True, verbose_name='Ativo')),
                ('data_cadastro', models.DateTimeField(auto_now_add=True)),
                ('empresa', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='funcionarios', to='core.empresa')),
            ],
            options={
                'verbose_name': 'Funcionário',
                'verbose_name_plural': 'Funcionários',
                'ordering': ['nome_completo'],
            },
        ),
        migrations.AlterField(
            model_name='ordemservico',
            name='funcionario_responsavel',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='os_responsavel', to='core.funcionario', verbose_name='Funcionário Responsável'),
        ),
    ]
