# Generated by Django 5.2.4 on 2026-07-13 13:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_alter_funcionario_cpf'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bomba',
            name='voltagem',
            field=models.CharField(max_length=50, verbose_name='Voltagem'),
        ),
    ]
