# Generated by Django 5.2.4 on 2026-07-31 19:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_altera_voltagem_bomba_para_texto'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ordemservico',
            name='numero_os',
            field=models.CharField(max_length=20, verbose_name='Nº OS'),
        ),
        migrations.AlterUniqueTogether(
            name='ordemservico',
            unique_together={('empresa', 'numero_os')},
        ),
    ]
